-- Auto-generated from live DB tags_t
-- Generated at 2026-05-19T18:10:27.510Z

INSERT INTO tags_t (category, tag)
VALUES
  ('agents', 'Agent Execution'),
  ('agents', 'Agent Memory'),
  ('agents', 'Agent Orchestration'),
  ('agents', 'Agent Planning'),
  ('agents', 'AI Agents'),
  ('agents', 'Autonomous Agents'),
  ('agents', 'BDI Agents'),
  ('agents', 'Deliberative Agents'),
  ('agents', 'Multi-Agent Systems'),
  ('agents', 'Reactive Agents'),
  ('agents', 'Task-specific Agents'),
  ('business', 'AI Startups'),
  ('business', 'AI Strategy'),
  ('business', 'Enterprise Adoption'),
  ('business', 'Enterprise AI'),
  ('business', 'Funding'),
  ('business', 'Go-to-Market'),
  ('business', 'Investments'),
  ('business', 'Market Trends'),
  ('business', 'Monetization'),
  ('business', 'ROI'),
  ('capabilities', 'Classification'),
  ('capabilities', 'Code Generation'),
  ('capabilities', 'Data Extraction'),
  ('capabilities', 'Image Generation'),
  ('capabilities', 'Information Retrieval'),
  ('capabilities', 'Named Entity Recognition'),
  ('capabilities', 'Planning'),
  ('capabilities', 'Question Answering'),
  ('capabilities', 'Reasoning'),
  ('capabilities', 'Search'),
  ('capabilities', 'Speech (TTS/ASR)'),
  ('capabilities', 'Summarization'),
  ('capabilities', 'Text Generation'),
  ('capabilities', 'Translation'),
  ('capabilities', 'Video Generation'),
  ('content_type', 'Analysis'),
  ('content_type', 'Benchmark'),
  ('content_type', 'Case Study'),
  ('content_type', 'Dataset Release'),
  ('content_type', 'News'),
  ('content_type', 'Opinion'),
  ('content_type', 'Podcast'),
  ('content_type', 'Research'),
  ('content_type', 'Tutorial'),
  ('content_type', 'Whitepaper'),
  ('context_layer', 'Context Injection'),
  ('context_layer', 'Context Windows'),
  ('context_layer', 'Document Chunking'),
  ('context_layer', 'Hybrid Retrieval'),
  ('context_layer', 'Memory Stores'),
  ('context_layer', 'RAG'),
  ('context_layer', 'Retrieval Systems'),
  ('context_layer', 'Semantic Search'),
  ('context_layer', 'Vector Databases'),
  ('core', 'AGI'),
  ('core', 'Artificial Intelligence'),
  ('core', 'Computer Vision'),
  ('core', 'Deep Learning'),
  ('core', 'Explainable AI'),
  ('core', 'Generative AI'),
  ('core', 'LLM'),
  ('core', 'Machine Learning'),
  ('core', 'Multimodal AI'),
  ('core', 'Natural Language Processing'),
  ('core', 'Neural Networks'),
  ('core', 'Neuro-symbolic AI'),
  ('core', 'Reinforcement Learning'),
  ('core', 'Representation Learning'),
  ('core', 'Self-supervised Learning'),
  ('core', 'Symbolic AI'),
  ('core', 'Transfer Learning'),
  ('dev_ops', 'Automated Testing'),
  ('dev_ops', 'CI/CD'),
  ('dev_ops', 'Continuous Training'),
  ('dev_ops', 'DataOps'),
  ('dev_ops', 'Deployment'),
  ('dev_ops', 'Evaluation / Evals'),
  ('dev_ops', 'LLMOps'),
  ('dev_ops', 'MLOps'),
  ('dev_ops', 'Model Monitoring'),
  ('dev_ops', 'Model Serving'),
  ('dev_ops', 'Model Versioning'),
  ('dev_ops', 'Observability'),
  ('ecosystem', 'Anthropic'),
  ('ecosystem', 'AWS AI'),
  ('ecosystem', 'Google DeepMind'),
  ('ecosystem', 'Hugging Face'),
  ('ecosystem', 'Meta AI'),
  ('ecosystem', 'Microsoft AI'),
  ('ecosystem', 'Mistral'),
  ('ecosystem', 'NVIDIA AI'),
  ('ecosystem', 'Open-source Community'),
  ('ecosystem', 'OpenAI'),
  ('ecosystem', 'Research Labs'),
  ('ecosystem', 'Startups'),
  ('infrastructure', 'AI Chips'),
  ('infrastructure', 'Cloud AI'),
  ('infrastructure', 'Cluster Management'),
  ('infrastructure', 'Compute Scaling'),
  ('infrastructure', 'Cooling Infrastructure'),
  ('infrastructure', 'Data Centers'),
  ('infrastructure', 'Data Pipelines'),
  ('infrastructure', 'Distributed Training'),
  ('infrastructure', 'Edge AI'),
  ('infrastructure', 'GPUs'),
  ('infrastructure', 'High-bandwidth Networking'),
  ('infrastructure', 'Kubernetes'),
  ('infrastructure', 'Storage Systems'),
  ('infrastructure', 'TPUs'),
  ('integration_layer', 'Adapters'),
  ('integration_layer', 'API Integrations'),
  ('integration_layer', 'Data Connectors'),
  ('integration_layer', 'Function Calling'),
  ('integration_layer', 'MCP'),
  ('integration_layer', 'Middleware'),
  ('integration_layer', 'Model Context Protocol'),
  ('integration_layer', 'Plugins'),
  ('integration_layer', 'SDKs'),
  ('integration_layer', 'Webhooks'),
  ('models', 'Anthropic Claude-family'),
  ('models', 'Baidu Ernie-family'),
  ('models', 'Cohere Models'),
  ('models', 'Diffusion Models'),
  ('models', 'EleutherAI GPT-NeoX'),
  ('models', 'Embeddings'),
  ('models', 'Falcon Models'),
  ('models', 'Fine-tuning'),
  ('models', 'Foundation Models'),
  ('models', 'Google Gemini-family'),
  ('models', 'Google PaLM-family'),
  ('models', 'Inference'),
  ('models', 'Meta Llama-family'),
  ('models', 'Mistral Models'),
  ('models', 'MosaicML MPT'),
  ('models', 'NVIDIA NeMo'),
  ('models', 'OpenAI GPT-family'),
  ('models', 'Quantization'),
  ('models', 'StabilityAI StableLM'),
  ('models', 'Transformers'),
  ('product', 'API Update'),
  ('product', 'Beta Release'),
  ('product', 'Changelog'),
  ('product', 'Feature Update'),
  ('product', 'Model Release'),
  ('product', 'Product Launch'),
  ('product', 'Release Notes'),
  ('product', 'Roadmap'),
  ('safety', 'Adversarial Robustness'),
  ('safety', 'AI Ethics'),
  ('safety', 'AI Safety'),
  ('safety', 'Alignment'),
  ('safety', 'Auditability'),
  ('safety', 'Bias'),
  ('safety', 'Content Moderation'),
  ('safety', 'Fairness'),
  ('safety', 'Governance'),
  ('safety', 'Incident Response'),
  ('safety', 'Privacy'),
  ('safety', 'Red Teaming'),
  ('safety', 'Security'),
  ('skills_layer', 'Actions'),
  ('skills_layer', 'Agent Skills'),
  ('skills_layer', 'Capabilities'),
  ('skills_layer', 'Custom Skills'),
  ('skills_layer', 'Prebuilt Skills'),
  ('skills_layer', 'Reusable Workflows'),
  ('skills_layer', 'Skill Libraries'),
  ('skills_layer', 'Skill Marketplace'),
  ('skills_layer', 'Skill Orchestration'),
  ('skills_layer', 'Skills'),
  ('skills_layer', 'Task Modules'),
  ('tools_layer', 'APIs as Tools'),
  ('tools_layer', 'Browser Automation'),
  ('tools_layer', 'CLI Tools'),
  ('tools_layer', 'Code Execution'),
  ('tools_layer', 'Computer Use'),
  ('tools_layer', 'Local Tool Execution'),
  ('tools_layer', 'Remote Tool Invocation'),
  ('tools_layer', 'Robotic Process Automation'),
  ('tools_layer', 'Tool Execution'),
  ('tools_layer', 'Tool Use'),
  ('workflows', 'Agent Workflows'),
  ('workflows', 'Automation'),
  ('workflows', 'CI/CD for AI'),
  ('workflows', 'Digital Workers'),
  ('workflows', 'Human-in-the-loop'),
  ('workflows', 'Process Automation'),
  ('workflows', 'SLA Management'),
  ('workflows', 'Task Automation'),
  ('workflows', 'Workflow Orchestration')
ON CONFLICT DO NOTHING;
